fragment UserInfo on Usuario {
  _id
  nome
  sobrenome
  email
  telefone
  nascimento
}

query Profile {
  profile{
    ...UserInfo
  }
}

mutation Register($input: UsuarioInput!){
  register(input: $input) {
    ...UserInfo
  }
}

mutation Login($email: String!, $senha: String!){
  login(email: $email, senha: $senha) {
    ...UserInfo
  }
}

mutation UpdateUsuario($id: ID!, $input: UsuarioInput!){
  updateUsuario(_id: $id, input: $input) {
    ...UserInfo
  }
}