query Profile {
  profile{
    _id
    nome
    sobrenome
    email
    telefone
    nascimento
  }
}

mutation Login($email: String!, $senha: String!) {
  login(email: $email, senha: $senha){
    _id
    nome
    sobrenome
    email
    telefone
    nascimento
  }
}

mutation Register($input: UsuarioInput!) {
  register(input: $input) {
    _id
    nome
    sobrenome
    email
    telefone
    nascimento
  }
}

mutation UpdateUsuario($id: ID!, $input: UsuarioInput!) {
  updateUsuario(_id: $id, input: $input) {
    _id
    nome
    sobrenome
    email
    telefone
    nascimento
  }
}